### ISSUE TITLE
No non animation trigger implemented

### ISSUE THREAD

**Issue by Chinyeins** [ukustra/SurfaceFootstepSystem#1]
Hey, I´ve downloaded and tested your plugin. It´s great. The only thing im missing is a way to make non-animation footsteps. 

I added code for this and would like to share it. Maybe it can be integrated int the plugin.

**Comment by ukustra** [comment]
Hi, I understand the idea of spawning footsteps without needing an animation, however, I'm not going to merge this PR. Spawning an additional Actor for the non-animation notify sounds like a redundant implementation - it should be done as a new BlueprintCallable function in FootstepComponent.

The data from the AnimNotify_SurfaceFootstep should be moved to a new structure in FootstepTypes.h and used both in AnimNotify and FootstepComponent for both types of notifies.
